package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Abogado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ABOGADO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ABOGADO_ID_SEQ", name = "ABOGADO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "strUsuario")
	private java.lang.String strUsuario;

	public Abogado() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStrUsuario() {
		return this.strUsuario;
	}

	public void setStrUsuario(java.lang.String strUsuario) {
		this.strUsuario = strUsuario;
	}

	public Abogado(java.lang.Long id, java.lang.String strUsuario) {
		this.id = id;
		this.strUsuario = strUsuario;
	}

}