package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DatosProcesoNotificacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DATOSPROCESONOTIFICACION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "DATOSPROCESONOTIFICACION_ID_SEQ", name = "DATOSPROCESONOTIFICACION_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "blnLevantarEstado")
	private java.lang.Boolean blnLevantarEstado;

	public DatosProcesoNotificacion() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Boolean getBlnLevantarEstado() {
		return this.blnLevantarEstado;
	}

	public void setBlnLevantarEstado(java.lang.Boolean blnLevantarEstado) {
		this.blnLevantarEstado = blnLevantarEstado;
	}

	public DatosProcesoNotificacion(java.lang.Long id,
			java.lang.Boolean blnLevantarEstado) {
		this.id = id;
		this.blnLevantarEstado = blnLevantarEstado;
	}

}