package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DatosProcesoProferirAuto implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("blnEnviarAGYNA")
	private java.lang.Boolean blnEnviarAGYNA;

	@org.kie.api.definition.type.Label("blnEnviarAExpediente")
	private java.lang.Boolean blnEnviarAExpediente;

	@org.kie.api.definition.type.Label("blnEsTraslado")
	private java.lang.Boolean blnEsTraslado;

	@org.kie.api.definition.type.Label("blnEsMedidaCautelar")
	private java.lang.Boolean blnEsMedidaCautelar;

	@org.kie.api.definition.type.Label("blnEsDemandaReconvencion")
	private java.lang.Boolean blnEsDemandaReconvencion;

	@org.kie.api.definition.type.Label("blnCasoResuelto")
	private java.lang.Boolean blnCasoResuelto;

	public DatosProcesoProferirAuto() {
	}

	public java.lang.Boolean getBlnEnviarAGYNA() {
		return this.blnEnviarAGYNA;
	}

	public void setBlnEnviarAGYNA(java.lang.Boolean blnEnviarAGYNA) {
		this.blnEnviarAGYNA = blnEnviarAGYNA;
	}

	public java.lang.Boolean getBlnEnviarAExpediente() {
		return this.blnEnviarAExpediente;
	}

	public void setBlnEnviarAExpediente(java.lang.Boolean blnEnviarAExpediente) {
		this.blnEnviarAExpediente = blnEnviarAExpediente;
	}

	public java.lang.Boolean getBlnEsTraslado() {
		return this.blnEsTraslado;
	}

	public void setBlnEsTraslado(java.lang.Boolean blnEsTraslado) {
		this.blnEsTraslado = blnEsTraslado;
	}

	public java.lang.Boolean getBlnEsMedidaCautelar() {
		return this.blnEsMedidaCautelar;
	}

	public void setBlnEsMedidaCautelar(java.lang.Boolean blnEsMedidaCautelar) {
		this.blnEsMedidaCautelar = blnEsMedidaCautelar;
	}

	public java.lang.Boolean getBlnEsDemandaReconvencion() {
		return this.blnEsDemandaReconvencion;
	}

	public void setBlnEsDemandaReconvencion(
			java.lang.Boolean blnEsDemandaReconvencion) {
		this.blnEsDemandaReconvencion = blnEsDemandaReconvencion;
	}

	public java.lang.Boolean getBlnCasoResuelto() {
		return this.blnCasoResuelto;
	}

	public void setBlnCasoResuelto(java.lang.Boolean blnCasoResuelto) {
		this.blnCasoResuelto = blnCasoResuelto;
	}

	public DatosProcesoProferirAuto(java.lang.Boolean blnEnviarAGYNA,
			java.lang.Boolean blnEnviarAExpediente,
			java.lang.Boolean blnEsTraslado,
			java.lang.Boolean blnEsMedidaCautelar,
			java.lang.Boolean blnEsDemandaReconvencion,
			java.lang.Boolean blnCasoResuelto) {
		this.blnEnviarAGYNA = blnEnviarAGYNA;
		this.blnEnviarAExpediente = blnEnviarAExpediente;
		this.blnEsTraslado = blnEsTraslado;
		this.blnEsMedidaCautelar = blnEsMedidaCautelar;
		this.blnEsDemandaReconvencion = blnEsDemandaReconvencion;
		this.blnCasoResuelto = blnCasoResuelto;
	}

}