package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DatosProcesoRevisionAbogado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Asignación Manual")
	private java.lang.Boolean blnAsignacionManual;

	@org.kie.api.definition.type.Label(value = "Traslado")
	private java.lang.Boolean blnTraslado;

	public DatosProcesoRevisionAbogado() {
	}

	public java.lang.Boolean getBlnAsignacionManual() {
		return this.blnAsignacionManual;
	}

	public void setBlnAsignacionManual(java.lang.Boolean blnAsignacionManual) {
		this.blnAsignacionManual = blnAsignacionManual;
	}

	public java.lang.Boolean getBlnTraslado() {
		return this.blnTraslado;
	}

	public void setBlnTraslado(java.lang.Boolean blnTraslado) {
		this.blnTraslado = blnTraslado;
	}

	public DatosProcesoRevisionAbogado(java.lang.Boolean blnAsignacionManual,
			java.lang.Boolean blnTraslado) {
		this.blnAsignacionManual = blnAsignacionManual;
		this.blnTraslado = blnTraslado;
	}

}