package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Estado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ESTADO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "ESTADO_ID_SEQ", name = "ESTADO_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "strCodigo")
	private java.lang.String strCodigo;

	public Estado() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStrCodigo() {
		return this.strCodigo;
	}

	public void setStrCodigo(java.lang.String strCodigo) {
		this.strCodigo = strCodigo;
	}

	public Estado(java.lang.Long id, java.lang.String strCodigo) {
		this.id = id;
		this.strCodigo = strCodigo;
	}

}