package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Expediente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Número")
	private java.lang.String strNumero;

	@org.kie.api.definition.type.Label(value = "Abogado")
	private co.gov.sic.sajur.entity.Abogado objAbogado;

	public Expediente() {
	}

	public java.lang.String getStrNumero() {
		return this.strNumero;
	}

	public void setStrNumero(java.lang.String strNumero) {
		this.strNumero = strNumero;
	}

	public co.gov.sic.sajur.entity.Abogado getObjAbogado() {
		return this.objAbogado;
	}

	public void setObjAbogado(co.gov.sic.sajur.entity.Abogado objAbogado) {
		this.objAbogado = objAbogado;
	}

	public Expediente(java.lang.String strNumero,
			co.gov.sic.sajur.entity.Abogado objAbogado) {
		this.strNumero = strNumero;
		this.objAbogado = objAbogado;
	}

}