package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ProcesoJuridico implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PROCESOJURIDICO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "PROCESOJURIDICO_ID_SEQ", name = "PROCESOJURIDICO_ID_GENERATOR")
	private java.lang.Long id;
	private java.lang.String strNumero;
	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "objAbogado")
	private co.gov.sic.sajur.entity.Abogado objAbogado;

	public ProcesoJuridico() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getStrNumero() {
		return this.strNumero;
	}

	public void setStrNumero(java.lang.String strNumero) {
		this.strNumero = strNumero;
	}

	public co.gov.sic.sajur.entity.Abogado getObjAbogado() {
		return this.objAbogado;
	}

	public void setObjAbogado(co.gov.sic.sajur.entity.Abogado objAbogado) {
		this.objAbogado = objAbogado;
	}

	public ProcesoJuridico(java.lang.Long id, java.lang.String strNumero,
			co.gov.sic.sajur.entity.Abogado objAbogado) {
		this.id = id;
		this.strNumero = strNumero;
		this.objAbogado = objAbogado;
	}

}