package co.gov.sic.sajur.entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Radicado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Año")
	private java.lang.String anio;
	@org.kie.api.definition.type.Label("Número Radicado")
	private java.lang.String numero;
	@org.kie.api.definition.type.Label("Número de Documento")
	private java.lang.String numeroDocumento;
	@org.kie.api.definition.type.Label("Código")
	private int codigo;
	@org.kie.api.definition.type.Label("Expedientes")
	private java.util.List<co.gov.sic.sajur.entity.Expediente> expedientes;

	public Radicado() {
	}

	public java.lang.String getAnio() {
		return this.anio;
	}

	public void setAnio(java.lang.String anio) {
		this.anio = anio;
	}

	public java.lang.String getNumero() {
		return this.numero;
	}

	public void setNumero(java.lang.String numero) {
		this.numero = numero;
	}

	public java.lang.String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(java.lang.String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	public java.util.List<co.gov.sic.sajur.entity.Expediente> getExpedientes() {
		return this.expedientes;
	}

	public void setExpedientes(
			java.util.List<co.gov.sic.sajur.entity.Expediente> expedientes) {
		this.expedientes = expedientes;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Radicado(java.lang.String anio, java.lang.String numero,
			java.lang.String numeroDocumento, int codigo,
			java.util.List<co.gov.sic.sajur.entity.Expediente> expedientes) {
		this.anio = anio;
		this.numero = numero;
		this.numeroDocumento = numeroDocumento;
		this.codigo = codigo;
		this.expedientes = expedientes;
	}

}